name: build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '6.26.1'
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Build docs
        run: pnpm docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PANDORALIBTOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          GIT_CONFIG_NAME: pandora-lib
          COMMIT_MESSAGE: website deploy
